spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 587
    username: 15e5b9092bee28
    password: 87a8f1652544ff
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  freemarker:
    template-loader-path: 'classpath:/templates'

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:~'
    username: panda
    password: 123
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: 9779
server:
  port: 9090